= Wan Khao Phansa (Bhuddist Lent) 
:hp-tags:
:hp-image: images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007713.jpg

This year, the eighth full moon of 2016 (in addition to being a Blue Moon) marks the beginning of a special time of year for Buddhists in Southeast Asia. Often referred to as “Buddhist Lent” or the “Rains Retreat” by westerners, this tradition corresponds to a three lunar month cycle when the region typically experiences heavy rains and farmers are planting their crops.

Monks and novices will stay in the same monastery or temple for the entire three-month period, venturing out only during the day (if at all) and always returning to the same temple to meditate and sleep. During this retreat, monks typically devote more time to meditation and deepening their understanding of the Dhamma – the truth taught by the Buddha.

Locals often practice a more ascetic lifestyle during this time period as well, often giving up meat, smoking or alcohol for a portion or all of the three months, spending more time giving alms on the streets, or visiting local temples to meditate.

Source: [Journey's Within Tour Company](https://www.journeys-within.com/travelblog/2015/07/22/what-is-buddhist-lent/)

image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007692.jpg[]
image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007701.jpg[]
image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007705.jpg[]
image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007713.jpg[]
image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007718.jpg[]
image::http://amritpatel.github.io/Things-Unseen/images/2016_07_17%202016_07_17%20Wan%20Khao%20Phansa%20(Bhuddist%20Lent)/R0007724.jpg[]
